- .github/workflows/ci-validate.yml
- change/@microsoft-cfp-template-a5d5984c-320c-4282-ba1e-20704a5ad687.json
- change/@microsoft-fast-cli-a1df441c-d8a9-4c0c-88bb-4e098ec884b7.json
- package-lock.json
- package.json
- packages/cfp-template/package-lock.json
- packages/cfp-template/package.json
- packages/cfp-template/template/fastconfig.json
- packages/cfp-template/template/playwright.config.ts
- packages/cfp-template/template/src/components/welcome/welcome.pw.spec.ts
- packages/fast-cli/.mocharc.json
- packages/fast-cli/README.md
- packages/fast-cli/package-lock.json
- packages/fast-cli/package.json
- packages/fast-cli/playwright.config.ts
- packages/fast-cli/src/cli.spec.ts
This change:
- Updates the `@microsoft/fast-cli` package to use playwright and its assertion library
- Updates the `webpack-dev-server` dependency in `@microsoft/cfp-template` to latest to fix security audit issues
- README update to reflect the different ways the package can be executed
> Fix high severity package errors, update testing to use playwright

- package-lock.json
- package.json
- website/CONTRIBUTING.md
- website/README.md
- website/build/constants.js
- website/build/docs.js
- website/build/gh-pages.js
- website/docs/initialize.md
- website/docs/introduction.md
- website/docs/sidebar.js
- website/docs/templates/category/index.html
- website/docs/templates/sidebar/index.html
- website/docs/templates/version/index.html
- website/docs/versions.json
- website/package-lock.json
- website/package.json
- website/server.js
- website/src/index.html
- website/src/templates/content.html
- website/src/templates/footer/index.html
- website/src/templates/meta/index.html
- website/src/templates/style/index.html
- website/src/templates/toolbar/index.html
- website/tsconfig.json
- website/webpack.config.js
This change adds a documentation site that can be built and used as a GitHub pages site.
> Add documentation site with initial docs and scaffolding

- .github/workflows/cd-gh-pages.yml
There was extra indenting in the yml workflow which seems to have created an issue when parsing for GitHub workflows.
> Correct yml workflow formatting

- .github/workflows/cd-gh-pages.yml
- .gitignore
To run a single workspace command the workspace needs to be specified, this has been updated for the GitHub Pages Deploy step in GitHub workflows.
The files in the docs file, which are generated, has also been gitignored.
> Updated the gitignore to include generated docs files and correct the workflow command

- .gitignore
- specs/fast-cli.md
This PR adds the initial draft spec for the FAST CLI, this is subject to change as new developments occur in the FAST Element 2.0 branch in the [fast](https://github.com/microsoft/fast) project.
This also updates the `.gitignore` file to correctly ignore docs files only from the root docs folder.
Closes #23 
Read through the specification to determine if this first draft makes sense for project creation and adding component code via templates.
- Add issues based on the specification to update the CLI with the new features
> Added a specification for the CLI

- change/@microsoft-fast-cli-76e548fd-9bd8-4168-92bf-9495023f27f6.json
- packages/fast-cli/src/cli.options.ts
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/cli.ts
- website/docs/add-a-design-system.md
- website/docs/sidebar.js
This change adds the `add-design-system` command.
Various error messages will be thrown if any of the required files are missing.
An additional cleanup change is to use variables to store the description of command line arguments and re-use them for user prompt messages.
Closes #28
> Added the add-design-system command

- change/@microsoft-fast-cli-e3f1ff4d-7b59-4eb9-bfd8-1600350d15c2.json
- packages/fast-cli/.eslintrc.cjs
- packages/fast-cli/src/components/README.md
- packages/fast-cli/src/components/blank/template/README.ts
- packages/fast-cli/src/components/blank/template/component.definition.ts
- packages/fast-cli/src/components/blank/template/component.pw.spec.ts
- packages/fast-cli/src/components/blank/template/component.stories.ts
- packages/fast-cli/src/components/blank/template/component.styles.ts
- packages/fast-cli/src/components/blank/template/component.template.ts
- packages/fast-cli/src/components/blank/template/component.ts
- packages/fast-cli/src/components/blank/template/define.ts
- packages/fast-cli/src/components/blank/template/fast.add-component.json
- packages/fast-cli/src/components/blank/template/fixture.ts
- packages/fast-cli/src/components/blank/template/index.ts
- packages/fast-cli/src/components/files.ts
- packages/fast-cli/src/components/options.ts
- packages/fast-cli/src/configuration/README.md
- packages/fast-cli/src/configuration/typings.d.ts
- packages/fast-cli/src/utilities/template.ts
This task is part of #30 as a blank component template is necessary as a starting point.
The blank template serves as a way to provide a way to inject a components name into a preconfigured template.
- Add the add component command
> Added a blank component template

- change/@microsoft-fast-cli-13a524ac-c8fc-4048-a699-58ff15386827.json
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/components/card/README.md
- packages/fast-cli/src/components/card/template/README.ts
- packages/fast-cli/src/components/card/template/component.definition.ts
- packages/fast-cli/src/components/card/template/component.pw.spec.ts
- packages/fast-cli/src/components/card/template/component.stories.ts
- packages/fast-cli/src/components/card/template/component.styles.ts
- packages/fast-cli/src/components/card/template/component.template.ts
- packages/fast-cli/src/components/card/template/component.ts
- packages/fast-cli/src/components/card/template/define.ts
- packages/fast-cli/src/components/card/template/fast.add-component.json
- packages/fast-cli/src/components/card/template/fixture.ts
- packages/fast-cli/src/components/card/template/index.ts
- packages/fast-cli/src/components/options.ts
Adds the foundation card component.
> Added the card component

- change/@microsoft-fast-cli-479de88c-f130-4189-bbdf-bafe28baa5a5.json
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/components/disclosure/README.md
- packages/fast-cli/src/components/disclosure/template/README.ts
- packages/fast-cli/src/components/disclosure/template/component.definition.ts
- packages/fast-cli/src/components/disclosure/template/component.pw.spec.ts
- packages/fast-cli/src/components/disclosure/template/component.stories.ts
- packages/fast-cli/src/components/disclosure/template/component.styles.ts
- packages/fast-cli/src/components/disclosure/template/component.template.ts
- packages/fast-cli/src/components/disclosure/template/component.ts
- packages/fast-cli/src/components/disclosure/template/define.ts
- packages/fast-cli/src/components/disclosure/template/fast.add-component.json
- packages/fast-cli/src/components/disclosure/template/fixture.ts
- packages/fast-cli/src/components/disclosure/template/index.ts
- packages/fast-cli/src/components/options.ts
Adds the foundation disclosure component.
> Added the disclosure component

- change/@microsoft-fast-cli-419f8bdd-3aae-4648-b038-c50fa295319d.json
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/components/number-field/README.md
- packages/fast-cli/src/components/number-field/template/README.ts
- packages/fast-cli/src/components/number-field/template/component.definition.ts
- packages/fast-cli/src/components/number-field/template/component.pw.spec.ts
- packages/fast-cli/src/components/number-field/template/component.stories.ts
- packages/fast-cli/src/components/number-field/template/component.styles.ts
- packages/fast-cli/src/components/number-field/template/component.template.ts
- packages/fast-cli/src/components/number-field/template/component.ts
- packages/fast-cli/src/components/number-field/template/define.ts
- packages/fast-cli/src/components/number-field/template/fast.add-component.json
- packages/fast-cli/src/components/number-field/template/fixture.ts
- packages/fast-cli/src/components/number-field/template/index.ts
- packages/fast-cli/src/components/options.ts
Adds the number-field foundation component.
Also applied a small cleanup to some of the component testing.
> Added the number-field component

- change/@microsoft-fast-cli-ca63fba5-69f5-4eff-9b5f-7a7f3ebb03b5.json
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/components/options.ts
- packages/fast-cli/src/components/progress-ring/README.md
- packages/fast-cli/src/components/progress-ring/template.pw.spec.ts
- packages/fast-cli/src/components/progress-ring/template/README.ts
- packages/fast-cli/src/components/progress-ring/template/component.definition.ts
- packages/fast-cli/src/components/progress-ring/template/component.pw.spec.ts
- packages/fast-cli/src/components/progress-ring/template/component.stories.ts
- packages/fast-cli/src/components/progress-ring/template/component.styles.ts
- packages/fast-cli/src/components/progress-ring/template/component.template.ts
- packages/fast-cli/src/components/progress-ring/template/component.ts
- packages/fast-cli/src/components/progress-ring/template/define.ts
- packages/fast-cli/src/components/progress-ring/template/fast.add-component.json
- packages/fast-cli/src/components/progress-ring/template/fixture.ts
- packages/fast-cli/src/components/progress-ring/template/index.ts
Adds the progress-ring foundation component.
Continued work on #31
> Added progress-ring component

- change/@microsoft-fast-cli-6553066f-b56e-4e58-bf30-89f23d5a473c.json
- packages/fast-cli/src/components/options.ts
- packages/fast-cli/src/components/progress/README.md
- packages/fast-cli/src/components/progress/template.pw.spec.ts
- packages/fast-cli/src/components/progress/template/README.ts
- packages/fast-cli/src/components/progress/template/component.definition.ts
- packages/fast-cli/src/components/progress/template/component.pw.spec.ts
- packages/fast-cli/src/components/progress/template/component.stories.ts
- packages/fast-cli/src/components/progress/template/component.styles.ts
- packages/fast-cli/src/components/progress/template/component.template.ts
- packages/fast-cli/src/components/progress/template/component.ts
- packages/fast-cli/src/components/progress/template/define.ts
- packages/fast-cli/src/components/progress/template/fast.add-component.json
- packages/fast-cli/src/components/progress/template/fixture.ts
- packages/fast-cli/src/components/progress/template/index.ts
Added the progress foundation component.
- Continued work on #31
> Added progress component

- change/@microsoft-fast-cli-21285a67-96cf-463c-8dac-e2861e33806b.json
- packages/fast-cli/src/components/dialog/template/README.ts
Fixed a documentation link in the dialog component README.
> Fixed the dialog component documentation link

- change/@microsoft-fast-cli-aa04c29b-458f-451d-a52b-752d59f0ed87.json
- packages/fast-cli/src/components/divider/README.md
- packages/fast-cli/src/components/divider/template.pw.spec.ts
- packages/fast-cli/src/components/divider/template/README.ts
- packages/fast-cli/src/components/divider/template/component.definition.ts
- packages/fast-cli/src/components/divider/template/component.pw.spec.ts
- packages/fast-cli/src/components/divider/template/component.stories.ts
- packages/fast-cli/src/components/divider/template/component.styles.ts
- packages/fast-cli/src/components/divider/template/component.template.ts
- packages/fast-cli/src/components/divider/template/component.ts
- packages/fast-cli/src/components/divider/template/define.ts
- packages/fast-cli/src/components/divider/template/fast.add-component.json
- packages/fast-cli/src/components/divider/template/fixture.ts
- packages/fast-cli/src/components/divider/template/index.ts
- packages/fast-cli/src/components/options.ts
Adds the divider foundation component.
> Added the divider component

- change/@microsoft-fast-cli-8909675e-1e23-4b55-b9df-c70b54b39add.json
- packages/fast-cli/src/components/badge/template.pw.spec.ts
- packages/fast-cli/src/components/blank/template.pw.spec.ts
- packages/fast-cli/src/components/card/template.pw.spec.ts
- packages/fast-cli/src/components/checkbox/template.pw.spec.ts
- packages/fast-cli/src/components/dialog/template.pw.spec.ts
- packages/fast-cli/src/components/disclosure/template.pw.spec.ts
- packages/fast-cli/src/components/divider/template.pw.spec.ts
- packages/fast-cli/src/components/flipper/template.pw.spec.ts
- packages/fast-cli/src/components/number-field/template.pw.spec.ts
- packages/fast-cli/src/components/progress-ring/template.pw.spec.ts
- packages/fast-cli/src/components/progress/template.pw.spec.ts
- packages/fast-cli/src/components/search/template.pw.spec.ts
- packages/fast-cli/src/test/helpers.ts
This moves the common test logic between components to the helper file for re-use.
> Refactored tests to use helper functions

- change/@microsoft-fast-cli-e2ef1965-526d-441f-8e5e-3c1fac5824cf.json
- package-lock.json
- packages/fast-cli/src/components/options.ts
- packages/fast-cli/src/components/switch/README.md
- packages/fast-cli/src/components/switch/template.pw.spec.ts
- packages/fast-cli/src/components/switch/template/README.ts
- packages/fast-cli/src/components/switch/template/component.definition.ts
- packages/fast-cli/src/components/switch/template/component.pw.spec.ts
- packages/fast-cli/src/components/switch/template/component.stories.ts
- packages/fast-cli/src/components/switch/template/component.styles.ts
- packages/fast-cli/src/components/switch/template/component.template.ts
- packages/fast-cli/src/components/switch/template/component.ts
- packages/fast-cli/src/components/switch/template/define.ts
- packages/fast-cli/src/components/switch/template/fast.add-component.json
- packages/fast-cli/src/components/switch/template/fixture.ts
- packages/fast-cli/src/components/switch/template/index.ts
Adds the switch foundation component.
- Continue work on #31
> Added the switch foundation component

- change/@microsoft-fast-cli-e5b24068-2260-4e69-a6c4-9fa4ddf7b932.json
- packages/fast-cli/src/components/options.ts
- packages/fast-cli/src/components/text-field/README.md
- packages/fast-cli/src/components/text-field/template.pw.spec.ts
- packages/fast-cli/src/components/text-field/template/README.ts
- packages/fast-cli/src/components/text-field/template/component.definition.ts
- packages/fast-cli/src/components/text-field/template/component.pw.spec.ts
- packages/fast-cli/src/components/text-field/template/component.stories.ts
- packages/fast-cli/src/components/text-field/template/component.styles.ts
- packages/fast-cli/src/components/text-field/template/component.template.ts
- packages/fast-cli/src/components/text-field/template/component.ts
- packages/fast-cli/src/components/text-field/template/define.ts
- packages/fast-cli/src/components/text-field/template/fast.add-component.json
- packages/fast-cli/src/components/text-field/template/fixture.ts
- packages/fast-cli/src/components/text-field/template/index.ts
Added the text-field foundation component.
- Continues work on #31
> Added the text-field component

- change/@microsoft-fast-cli-ead87ab3-aaf6-41a4-b224-54bc6e257a28.json
- packages/fast-cli/src/components/card/template/component.ts
- packages/fast-cli/src/components/disclosure/template/component.ts
- packages/fast-cli/src/components/flipper/template/component.definition.ts
- packages/fast-cli/src/components/number-field/template/component.definition.ts
- packages/fast-cli/src/components/number-field/template/component.ts
- packages/fast-cli/src/components/search/template/component.definition.ts
- packages/fast-cli/src/components/search/template/component.ts
After doing some re-assessment of added foundation components it was found that a few were missing additional class logic, seemingly related to specific styling, and a few had extra elements baked into the definition.
Related to #31
> Added some missing class logic to components that have deviated from foundation

- change/@microsoft-fast-cli-04f71634-b5b4-4c02-973b-3bd1ca987c14.json
- packages/fast-cli/src/components/options.ts
- packages/fast-cli/src/components/tooltip/README.md
- packages/fast-cli/src/components/tooltip/template.pw.spec.ts
- packages/fast-cli/src/components/tooltip/template/README.ts
- packages/fast-cli/src/components/tooltip/template/component.definition.ts
- packages/fast-cli/src/components/tooltip/template/component.pw.spec.ts
- packages/fast-cli/src/components/tooltip/template/component.stories.ts
- packages/fast-cli/src/components/tooltip/template/component.styles.ts
- packages/fast-cli/src/components/tooltip/template/component.template.ts
- packages/fast-cli/src/components/tooltip/template/component.ts
- packages/fast-cli/src/components/tooltip/template/define.ts
- packages/fast-cli/src/components/tooltip/template/fast.add-component.json
- packages/fast-cli/src/components/tooltip/template/fixture.ts
- packages/fast-cli/src/components/tooltip/template/index.ts
This adds the tooltip foundation component.
- Continues work on #31
> Added the tooltip foundation component

- change/@microsoft-fast-cli-6f53357a-c211-4ef4-aa2a-9a4b938dd5af.json
- packages/fast-cli/src/components/calendar/README.md
- packages/fast-cli/src/components/calendar/template.pw.spec.ts
- packages/fast-cli/src/components/calendar/template/README.ts
- packages/fast-cli/src/components/calendar/template/component.definition.ts
- packages/fast-cli/src/components/calendar/template/component.pw.spec.ts
- packages/fast-cli/src/components/calendar/template/component.stories.ts
- packages/fast-cli/src/components/calendar/template/component.styles.ts
- packages/fast-cli/src/components/calendar/template/component.template.ts
- packages/fast-cli/src/components/calendar/template/component.ts
- packages/fast-cli/src/components/calendar/template/define.ts
- packages/fast-cli/src/components/calendar/template/fast.add-component.json
- packages/fast-cli/src/components/calendar/template/fixture.ts
- packages/fast-cli/src/components/calendar/template/index.ts
- packages/fast-cli/src/components/options.ts
This change adds the calendar foundation component.
Continued work on #31
- Continue adding components for #31
> Added the calendar component

- change/@microsoft-fast-cli-45b1e283-3036-4d22-8f7e-b50ef14d162f.json
- package-lock.json
- packages/fast-cli/playwright.config.ts
- packages/fast-cli/src/cli.options.ts
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/cli.ts
- packages/fast-cli/src/test/helpers.ts
- website/docs/add-a-component.md
- website/docs/configure.md
This change allows various commands to exercise the `-y` to apply defaults instead of prompting or using command line arguments for commands that contain defaults.
> Added default option logic

- change/@microsoft-fast-cli-41a7fc8f-fcf7-4a20-92ae-c4cc4bfb409b.json
- package-lock.json
- packages/adaptive-ui/package.json
- packages/fast-cli/package.json
This change removes unnecessary dependencies which were partially responsible for duplicate dependency issues.
> Partially resolves an issue with duplicated dependencies

- packages/cfp-template/template/src/design-system.ts
- packages/fast-cli/src/components/accordion-item/template/component.styles.ts
- packages/fast-cli/src/components/badge/template/component.styles.ts
- packages/fast-cli/src/components/checkbox/template/component.styles.ts
- packages/fast-cli/src/components/disclosure/template/component.styles.ts
- packages/fast-cli/src/components/flipper/template/component.styles.ts
- packages/fast-cli/src/components/progress-ring/template/component.styles.ts
- packages/fast-cli/src/components/search/template/component.styles.ts
- packages/fast-cli/src/components/switch/template/component.styles.ts
- packages/fast-cli/src/components/text-area/template/component.styles.ts
Added styling for disabledOpacity and heightNumber and other cleanup
> Style pass 1

- change/@microsoft-fast-cli-f248f4ff-9726-420c-a71c-d6e98c97526f.json
- packages/fast-cli/src/cli.errors.ts
- packages/fast-cli/src/cli.fs.spec.ts
- packages/fast-cli/src/cli.fs.ts
- packages/fast-cli/src/cli.globals.ts
- packages/fast-cli/src/cli.options.ts
- packages/fast-cli/src/cli.prompt.ts
- packages/fast-cli/src/cli.ts
- packages/fast-cli/src/cli.types.ts
- packages/fast-cli/src/cli.utilities.spec.ts
- packages/fast-cli/src/cli.utilities.ts
- packages/fast-cli/src/templates/design-system.ts
This work extracts the async utilities (utilities using `fs-extra` and `prompts`) as part of the overall abstraction that will occur for smoother testing of the CLI.
Partial work for #78
Note that the logic is essentially the same, only moved.
- Abstraction for the bulk of the CLI logic to deal with testing and simplification.
> Moved the async logic for future testing scenarios

- beachball.config.js
- change/@microsoft-cfp-template-88dae062-57c6-402b-b80c-ad69a0b7ae30.json
- change/@microsoft-fast-cli-e6fa93c4-efec-43e9-a82e-f7ee6bb76ea9.json
- packages/cfp-template/package.json
- packages/fast-cli/package.json
This change sets the initial published versions of the packages to `1.0.0-alpha.1`, and sets the version bumping to simultaneously bump all packages.
See: https://microsoft.github.io/beachball/concepts/groups.html for how the version bumping can be grouped.
> Set the version to alpha for packages and set packages to version together

- CONTRIBUTING.md
A contributor discovered that npm 7 does not work with this npm workspace setup, the contributing docs have been updated.
> Updated the contributing docs with newer npm version

- change/@microsoft-fast-cli-c69acb5c-e907-4b1d-b5a8-7ba62ef5a71c.json
- packages/fast-cli/.npmignore
This change adds the `.npmignore` file to the `@microsoft/fast-cli` package which was missing.
> Added an .npmignore file

- change/@microsoft-cfp-template-d0613ed1-f8e9-4021-995c-43640e5be141.json
- change/@microsoft-create-fast-project-0b262aae-6049-45b7-82e3-0f155d3f8e37.json
- change/@microsoft-fast-cli-1e1f0bef-846c-49d7-87eb-9174e8f9940c.json
- package-lock.json
- packages/cfp-template/package.json
- packages/create-fast-project/README.md
- packages/create-fast-project/package.json
- packages/create-fast-project/src/create.ts
- packages/create-fast-project/tsconfig.json
- packages/fast-cli/package.json
This change does the following:
- Adds a quick installation and initialization package
- Updates the package.json files to point to the fast-cli repository
Resolves #2 
The build will fail until the other packages have been published.
- Plan next steps for MVP
> Add new create FAST project package

- change/@microsoft-fast-cli-c7d49f96-2501-40d1-a5af-6b454dff121b.json
- package-lock.json
- packages/fast-cli/package.json
TypeScript is using an export from tslib, it therefore has to be added as a dependency to the `@microsoft/fast-cli` package.
> Add tslib as a dependency

- change/@microsoft-create-fast-project-e6a09cce-9078-43b9-baf1-082b8414bb66.json
- package-lock.json
- packages/create-fast-project/package.json
This adds a missing necessary dependency for the initialization from the `@microsoft/create-fast-project` package.
> Added the default template as a dependency

- README.md
- website/src/templates/footer/index.html
Added a contribute section to the README and made the HTML look a bit better.
- [X ] I have tested my changes.
- [ X] I have updated the project documentation to reflect my changes.
> Added contributing section to README.md and made HTML less spaced out 

- change/@microsoft-fast-cli-e67e449a-7f61-4b72-a6d6-552065eeee1d.json
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/cli.ts
- packages/fast-cli/src/components/components.pw.spec.ts
- packages/fast-cli/src/test/helpers.ts
The package resolving for both templates for init and components were not resolving correctly, this adds better local package vs remote checking logic.
Note that although tests have been added for remote, these tests are skipped as they can only be run locally. The GitHub build gate does not allow installation of packages via child processes.
> Fixed local vs remote package resolving logic

- change/@microsoft-cfp-template-fd6954bb-192d-48fb-a293-b8efd9ae2f54.json
- change/@microsoft-fast-cli-29b38233-43cf-4560-bee4-b66089525fe4.json
- packages/cfp-template/template/README.md
- packages/fast-cli/src/cli.ts
The installation of the playwright browsers in the CLI causes async issues with project creation/initializations, so this has been removed and guidance has been added to the default template.
> Remove the playwright browser install

- website/docs/add-a-foundation-component.md
Fixed a misspelling in the docs site.
> Fixed a documentation site typo

- change/@microsoft-cfp-template-c742a270-d0a9-4e12-a2f7-07c7fd377718.json
- change/@microsoft-fast-cli-8b662bff-8a3a-4ae1-a913-559d7722f6b9.json
- packages/cfp-template/template/fast.init.json
- packages/fast-cli/src/cli.options.ts
- packages/fast-cli/src/cli.ts
- website/docs/templates/project.md
This change adds the following message to the `@microsoft/cfp-template` package:
This will provide some additional feedback to the user or else the process will just end after installation and copying of files.
> Added an optional initialization completed message

- change/@microsoft-eslint-plugin-fast-cli-migrate-bffc86c4-9503-4baa-9290-e736d8244fa4.json
- packages/eslint-plugin-fast-cli-migrate/README.md
- packages/eslint-plugin-fast-cli-migrate/src/configs/1.0.0-alpha.1.ts
- packages/eslint-plugin-fast-cli-migrate/src/index.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--components-index.md
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--components-index.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--components-index.invalid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--components-index.valid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/rules/rules.spec.ts
This rule updates the components `index.ts` file during migration.
Continuing work on #41
This change is related to the ESLint migration package and updates the `index.ts` file located in the components folder.
- Continue adding migrate rules.
> Added the components index rule

- change/@microsoft-eslint-plugin-fast-cli-migrate-2d7a85ba-34ed-4b91-91c9-8e0cadee9196.json
- packages/eslint-plugin-fast-cli-migrate/README.md
- packages/eslint-plugin-fast-cli-migrate/src/configs/1.0.0-alpha.1.ts
- packages/eslint-plugin-fast-cli-migrate/src/index.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--define.md
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--define.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--define.invalid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--define.valid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/rules/rules.spec.ts
This change adds a rule for updating the `define.ts` file. This is another rule used for upgrading primarily via the FAST CLI `migrate` command.
See previous PR for more details #104
> Added the define rule

- beachball.config.js
This change removes the `*.spec.ts`, `README.ts`, and `*.md` files from the check for changes used by `beachball`. As these files do not affect the published package in terms of the functional exports, they should not require changefiles.
Unblocks #102
> Remove markdown and test files from beachball change check

- change/@microsoft-eslint-plugin-fast-cli-migrate-d67f67b0-4285-4816-9981-d52f6de24459.json
- packages/eslint-plugin-fast-cli-migrate/README.md
- packages/eslint-plugin-fast-cli-migrate/src/configs/1.0.0-alpha.1.ts
- packages/eslint-plugin-fast-cli-migrate/src/index.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--definition.md
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--definition.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/utilities/string.spec.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/utilities/string.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--definition.invalid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--definition.valid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/rules/rules.spec.ts
This change adds a rule to update components `*.definition.ts` files for the newest version update.
Continues work on #41
> Add the ESLint migrate definition rule for 1.0.0-alpha.1

- change/@microsoft-eslint-plugin-fast-cli-migrate-fa67da93-ceaf-4eff-942f-aac1b8c075ea.json
- packages/eslint-plugin-fast-cli-migrate/README.md
- packages/eslint-plugin-fast-cli-migrate/src/configs/1.0.0-alpha.1.ts
- packages/eslint-plugin-fast-cli-migrate/src/index.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--design-system.md
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--design-system.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--design-system.invalid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--design-system.valid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/rules/rules.spec.ts
This rule migrates the `design-system.ts` file to the updated code following updates for `@microsoft/fast-foundation`.
Continues work on #41
> Add the ESLint migrate design system rule for 1.0.0-alpha.1

- website/docs/initialize.md
Added the missing `@microsoft` scope to the initialize documentation.
> Added scope to website documentation

- change/@microsoft-fast-cli-da07c2b0-1c27-4498-bf5b-64e471205053.json
- packages/fast-cli/.npmignore
The template spec files are needed for the npm package as they are used in the CLI to generate spec files for components.
> Added a line to ensure template spec files are not ignored

- website/docs/add-a-foundation-component.md
This change updates the documentation for the `add-foundation-component` FAST CLI command so that the list of the components is correct as of the present iteration, and that the use of the `-all` option is separated as they cannot be used together.
Received community feedback that this section of the documentation was confusing so this should be more clear.
> Updated the foundation component list and command option documentation

- change/@microsoft-eslint-plugin-fast-cli-migrate-a245a3c0-23ac-4087-892c-fd0787510e65.json
- packages/eslint-plugin-fast-cli-migrate/README.md
- packages/eslint-plugin-fast-cli-migrate/src/configs/1.0.0-alpha.1.ts
- packages/eslint-plugin-fast-cli-migrate/src/index.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--index.md
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--index.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--index.invalid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--index.valid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/rules/rules.spec.ts
This change adds the ESLint rule for migrating the index file.
Continues work on #41
> Add the ESLint migrate index rule for 1.0.0-alpha.1 

- change/@microsoft-eslint-plugin-fast-cli-migrate-7375ddaf-28d0-447c-b97b-136df3bda9d9.json
- packages/eslint-plugin-fast-cli-migrate/README.md
- packages/eslint-plugin-fast-cli-migrate/src/configs/1.0.0-alpha.1.ts
- packages/eslint-plugin-fast-cli-migrate/src/index.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--stories.md
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--stories.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--stories.invalid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--stories.valid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/rules/rules.spec.ts
This adds a rule to convert `*.stories.ts` file which are used in storybook.
Continued work on #41
> Added stories rule

- change/@microsoft-eslint-plugin-fast-cli-migrate-a3226aff-e010-495f-bf0e-930f0f07541b.json
- packages/eslint-plugin-fast-cli-migrate/README.md
- packages/eslint-plugin-fast-cli-migrate/src/configs/1.0.0-alpha.1.ts
- packages/eslint-plugin-fast-cli-migrate/src/index.ts
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--template.md
- packages/eslint-plugin-fast-cli-migrate/src/rules/1.0.0-alpha.1--template.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--template.invalid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/files/1.0.0-alpha.1--template.valid.ts
- packages/eslint-plugin-fast-cli-migrate/src/tests/rules/rules.spec.ts
This change adds a rule for the `*.template.ts` files.
Continued work on $41
> Added template rule

- change/@microsoft-fast-cli-e8c1f38b-5aa4-4bd5-9e9a-4dc580d0d0e1.json
- packages/fast-cli/src/cli.globals.ts
- packages/fast-cli/src/cli.spec.ts
- packages/fast-cli/src/cli.ts
- packages/fast-cli/src/test/helpers.ts
- website/docs/sidebar.js
- website/docs/version.md
This adds a `version` command to check the current version of the CLI.
Begins work on #103
> Added a version command

- change/@microsoft-fast-cli-8227cced-ae58-4c38-8e44-e08d1b8813e6.json
- packages/fast-cli/src/cli.errors.ts
- packages/fast-cli/src/cli.fs.spec.ts
- packages/fast-cli/src/cli.globals.ts
- packages/fast-cli/src/cli.ts
This removes the last references to "node_modules" folder and uses dynamic imports instead allowing module resolution.
Closes #121
> Updated to used dynamic imports for module resolution

- change/@microsoft-fast-cli-27141e17-fad3-4fa0-9a6f-4da9c9f618f5.json
- packages/fast-cli/src/cli.migrate.spec.ts
- packages/fast-cli/src/cli.migrate.ts
This change adds a version control dictionary which will act as a migration matrix when the `migrate` command is used.
Related to #41 
- Add the actual migrate command
- Update all projects and components to the new version using the migrate command
> Add migration matrix for version control

- CONTRIBUTING.md
- ONBOARDING.md
This change adds an onboarding markdown file that is linked from the `CONTRIBUTING.md` file as a supplement for new contributors.
Please read through and make notes if anything is confusing or needs clarity from the perspective from a new contributor.
> Added an onboarding document
